// Mock titles con poster paths reales de TMDB
// Usado como fallback si la API de TMDB no está disponible.
// posterPath copiado de TMDB para los títulos del onboarding.

import type { NormalizedTitle } from '../services/tmdb';

export const MOCK_TITLES: NormalizedTitle[] = [
  { id: 278,    tmdbId: 278,    type: 'movie', title: 'The Shawshank Redemption', year: 1994, genres: ['Drama'], rating: 9.3, posterPath: '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg', synopsis: 'Dos hombres unidos por la amistad en la dura prisión de Shawshank. Una historia de esperanza.' },
  { id: 238,    tmdbId: 238,    type: 'movie', title: 'The Godfather', year: 1972, genres: ['Crimen', 'Drama'], rating: 9.2, posterPath: '/3bhkrj58Vtu7enYsLegHzqn3CDu.jpg', synopsis: 'El patriarca de una poderosa familia mafiosa le transfiere el control de su imperio a su reticente hijo.' },
  { id: 13,     tmdbId: 13,     type: 'movie', title: 'Forrest Gump', year: 1994, genres: ['Drama', 'Romance', 'Comedia'], rating: 8.8, posterPath: '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg', synopsis: 'Un hombre con un coeficiente intelectual bajo es testigo accidental de los grandes eventos históricos del siglo XX.' },
  { id: 105,    tmdbId: 105,    type: 'movie', title: 'Back to the Future', year: 1985, genres: ['Aventura', 'Comedia', 'Ciencia Ficción'], rating: 8.5, posterPath: '/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg', synopsis: 'Un adolescente viaja accidentalmente en el tiempo hasta 1955 con la ayuda de un excéntrico científico.' },
  { id: 329,    tmdbId: 329,    type: 'movie', title: 'Jurassic Park', year: 1993, genres: ['Aventura', 'Ciencia Ficción'], rating: 8.2, posterPath: '/oU7Oq2kFAAlGqbU4VoAE36g4hoI.jpg', synopsis: 'Un parque de atracciones poblado de dinosaurios clonados se convierte en una pesadilla cuando las bestias escapan.' },
  { id: 680,    tmdbId: 680,    type: 'movie', title: 'Pulp Fiction', year: 1994, genres: ['Crimen', 'Drama'], rating: 8.9, posterPath: '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg', synopsis: 'Las historias entrelazadas de criminales, boxeadores y asesinos en el Los Ángeles criminal.' },
  { id: 120,    tmdbId: 120,    type: 'movie', title: 'The Lord of the Rings: The Fellowship of the Ring', year: 2001, genres: ['Aventura', 'Fantasía'], rating: 8.8, posterPath: '/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg', synopsis: 'Un hobbit emprende un viaje épico para destruir el Anillo Único y salvar la Tierra Media.' },
  { id: 22,     tmdbId: 22,     type: 'movie', title: 'Pirates of the Caribbean: The Curse of the Black Pearl', year: 2003, genres: ['Aventura', 'Fantasía', 'Acción'], rating: 8.0, posterPath: '/z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg', synopsis: 'El excéntrico capitán Jack Sparrow se une a un herrero para rescatar a la hija del gobernador de unos piratas malditos.' },
  { id: 155,    tmdbId: 155,    type: 'movie', title: 'The Dark Knight', year: 2008, genres: ['Acción', 'Drama', 'Crimen'], rating: 9.0, posterPath: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg', synopsis: 'Batman enfrenta a El Joker, un criminal que quiere sumir Gotham en el caos.' },
  { id: 27205,  tmdbId: 27205,  type: 'movie', title: 'Inception', year: 2010, genres: ['Acción', 'Ciencia Ficción', 'Thriller'], rating: 8.8, posterPath: '/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg', synopsis: 'Un ladrón especializado en robar secretos del subconsciente acepta implantar una idea en la mente de alguien.' },
  { id: 24428,  tmdbId: 24428,  type: 'movie', title: 'The Avengers', year: 2012, genres: ['Acción', 'Aventura', 'Ciencia Ficción'], rating: 8.0, posterPath: '/RYMX2wpn7rwYjkMT6nBsLzefrG.jpg', synopsis: 'Los superhéroes más poderosos del mundo deben unirse para detener al dios Loki y su ejército alienígena.' },
  { id: 245891, tmdbId: 245891, type: 'movie', title: 'John Wick', year: 2014, genres: ['Acción', 'Thriller'], rating: 7.4, posterPath: null, synopsis: 'Un exasesino regresa al mundo criminal para vengarse de los hombres que le mataron su perro.' },
  { id: 129,    tmdbId: 129,    type: 'movie', title: 'El viaje de Chihiro', year: 2001, genres: ['Animación', 'Fantasía'], rating: 8.6, posterPath: '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg', synopsis: 'Una niña queda atrapada en un mundo mágico y debe trabajar para liberar a sus padres.' },
  { id: 18785,  tmdbId: 18785,  type: 'movie', title: 'The Hangover', year: 2009, genres: ['Comedia'], rating: 7.7, posterPath: null, synopsis: 'Tres amigos despiertan en Las Vegas sin recordar nada de la noche anterior — ni al novio que deben encontrar.' },
  { id: 2316,   tmdbId: 2316,   type: 'tv',    title: 'The Office', year: 2005, genres: ['Comedia'], rating: 9.0, posterPath: '/7DJKHzAi83BmQrWLrYYOqcoKfhR.jpg', synopsis: 'El día a día en las oficinas de Dunder Mifflin, filmado como un documental.' },
  { id: 61662,  tmdbId: 61662,  type: 'tv',    title: "Schitt's Creek", year: 2015, genres: ['Comedia'], rating: 8.4, posterPath: '/iRfSzrPS5VYWQv7KVSEg2BZZL6C.jpg', synopsis: 'Una familia millonaria pierde su fortuna y debe mudarse a un pueblo que compraron como chiste.' },
  { id: 67070,  tmdbId: 67070,  type: 'tv',    title: 'Fleabag', year: 2016, genres: ['Comedia', 'Drama'], rating: 8.7, posterPath: '/27vEYsRKa3eAniwmoccOoluEXQ1.jpg', synopsis: 'Una mujer navega el caos de la vida moderna en Londres con humor e irreverencia.' },
  { id: 176,    tmdbId: 176,    type: 'movie', title: 'Saw', year: 2004, genres: ['Terror', 'Thriller', 'Misterio'], rating: 7.6, posterPath: null, synopsis: 'Dos hombres despiertan encadenados en un cuarto de baño con el cadáver de un desconocido — y un mensaje del Jigsaw.' },
  { id: 419430, tmdbId: 419430, type: 'movie', title: 'Get Out', year: 2017, genres: ['Terror', 'Thriller'], rating: 7.7, posterPath: '/mE24wUCfjK8AoBBjaMjho7Rczr7.jpg', synopsis: 'Un hombre afroamericano visita a los padres de su novia blanca y descubre algo perturbador.' },
  { id: 93405,  tmdbId: 93405,  type: 'tv',    title: 'Squid Game', year: 2021, genres: ['Drama', 'Thriller'], rating: 8.0, posterPath: '/1QdXdRYfktUSONkl1oD5gc6Be0s.jpg', synopsis: 'Cientos de jugadores desesperados aceptan participar en juegos infantiles con consecuencias mortales.' },
  { id: 1396,   tmdbId: 1396,   type: 'tv',    title: 'Breaking Bad', year: 2008, genres: ['Drama', 'Crimen'], rating: 9.5, posterPath: '/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg', synopsis: 'Un profesor de química con cáncer comienza a fabricar metanfetamina con un ex alumno.' },
  { id: 496243, tmdbId: 496243, type: 'movie', title: 'Parasite', year: 2019, genres: ['Thriller', 'Drama', 'Comedia'], rating: 8.5, posterPath: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', synopsis: 'La codiciosa familia Ki-taek se infiltra en la vida de la próspera familia Park.' },
  { id: 66732,  tmdbId: 66732,  type: 'tv',    title: 'Stranger Things', year: 2016, genres: ['Ciencia Ficción', 'Terror', 'Drama'], rating: 8.7, posterPath: '/49WJfeN0moxb9IPfGn8AIqMGskD.jpg', synopsis: 'Cuando un niño desaparece, su pueblo descubre una conspiración que involucra experimentos secretos y criaturas sobrenaturales.' },
  { id: 95396,  tmdbId: 95396,  type: 'tv',    title: 'Severance', year: 2022, genres: ['Thriller', 'Ciencia Ficción'], rating: 8.7, posterPath: '/pPHpeI2X1qEd1CS1SeyrdhZ4qnT.jpg', synopsis: 'Empleados cuya memoria laboral y personal está quirúrgicamente dividida en dos mundos separados.' },
  { id: 97546,  tmdbId: 97546,  type: 'tv',    title: 'Ted Lasso', year: 2020, genres: ['Comedia', 'Drama'], rating: 8.8, posterPath: '/5fhZdwP1DVJ0FyVH6vrFdHwpXIn.jpg', synopsis: 'Un entrenador de fútbol americano sin experiencia es contratado para dirigir un club inglés.' },
  { id: 136315, tmdbId: 136315, type: 'tv',    title: 'The Bear', year: 2022, genres: ['Comedia', 'Drama'], rating: 8.7, posterPath: null, synopsis: 'Un chef de alta cocina regresa a Chicago para hacerse cargo del restaurante de sándwiches de su familia.' },
  { id: 1399,   tmdbId: 1399,   type: 'tv',    title: 'Game of Thrones', year: 2011, genres: ['Fantasía', 'Drama'], rating: 9.2, posterPath: '/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg', synopsis: 'Varias familias luchan por el control del Trono de Hierro en los Siete Reinos.' },
  { id: 872585, tmdbId: 872585, type: 'movie', title: 'Oppenheimer', year: 2023, genres: ['Drama', 'Historia'], rating: 8.5, posterPath: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg', synopsis: 'La historia del padre de la bomba atómica y el Proyecto Manhattan.' },
  { id: 693134, tmdbId: 693134, type: 'movie', title: 'Dune: Part Two', year: 2024, genres: ['Ciencia Ficción', 'Aventura'], rating: 8.5, posterPath: '/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg', synopsis: 'Paul Atreides se une a los Fremen y busca venganza contra los que destruyeron a su familia.' },
  { id: 126308, tmdbId: 126308, type: 'tv',    title: 'Shōgun', year: 2024, genres: ['Drama', 'Historia'], rating: 8.9, posterPath: '/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg', synopsis: 'Un navegante inglés llega al Japón feudal y se convierte en aliado de un señor de la guerra.' },
];
