// Mock titles con poster paths reales de TMDB
// Usado como fallback si la API de TMDB no está disponible.
// posterPath copiado de TMDB para los títulos del onboarding.

import type { NormalizedTitle } from '../services/tmdb';

export const MOCK_TITLES: NormalizedTitle[] = [
  { id: 278,    tmdbId: 278,    type: 'movie', title: 'The Shawshank Redemption', year: 1994, genres: ['Drama'], rating: 9.3, posterPath: '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg', synopsis: 'Dos hombres unidos por la amistad en la dura prisión de Shawshank. Una historia de esperanza.' },
  { id: 4613,   tmdbId: 4613,   type: 'tv',    title: 'Band of Brothers', year: 2001, genres: ['Drama', 'Bélica'], rating: 9.4, posterPath: '/pGzV187ogXzgJrvPRy2YPi29ofH.jpg', synopsis: 'La historia de la Compañía Easy del 506° Regimiento de Infantería Paracaidista durante la Segunda Guerra Mundial.' },
  { id: 87108,  tmdbId: 87108,  type: 'tv',    title: 'Chernobyl', year: 2019, genres: ['Drama', 'Historia'], rating: 9.3, posterPath: '/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg', synopsis: 'La historia real del desastre nuclear de 1986 en Chernóbil.' },
  { id: 76331,  tmdbId: 76331,  type: 'tv',    title: 'Succession', year: 2018, genres: ['Drama', 'Comedia'], rating: 8.9, posterPath: '/z0XiwdrCQ9yVIr4O0pxzaAYRxdW.jpg', synopsis: 'La familia Roy lucha por el control de su imperio mediático mientras el patriarca enferma.' },
  { id: 126308, tmdbId: 126308, type: 'tv',    title: 'Shōgun', year: 2024, genres: ['Drama', 'Historia'], rating: 8.9, posterPath: '/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg', synopsis: 'Un navegante inglés llega al Japón feudal y se convierte en aliado de un señor de la guerra.' },
  { id: 872585, tmdbId: 872585, type: 'movie', title: 'Oppenheimer', year: 2023, genres: ['Drama', 'Historia'], rating: 8.5, posterPath: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg', synopsis: 'La historia del padre de la bomba atómica y el Proyecto Manhattan.' },
  { id: 1396,   tmdbId: 1396,   type: 'tv',    title: 'Breaking Bad', year: 2008, genres: ['Drama', 'Crimen'], rating: 9.5, posterPath: '/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg', synopsis: 'Un profesor de química con cáncer comienza a fabricar metanfetamina con un ex alumno.' },
  { id: 1398,   tmdbId: 1398,   type: 'tv',    title: 'The Sopranos', year: 1999, genres: ['Drama', 'Crimen'], rating: 9.2, posterPath: '/rTc7ZXdroqjkKivFPvCPX0Ru7uw.jpg', synopsis: 'Tony Soprano equilibra su vida familiar con su papel como jefe de la mafia de Nueva Jersey.' },
  { id: 680,    tmdbId: 680,    type: 'movie', title: 'Pulp Fiction', year: 1994, genres: ['Crimen', 'Drama'], rating: 8.9, posterPath: '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg', synopsis: 'Las historias entrelazadas de criminales, boxeadores y un par de asesinos en el Los Ángeles criminal.' },
  { id: 496243, tmdbId: 496243, type: 'movie', title: 'Parasite', year: 2019, genres: ['Thriller', 'Drama', 'Comedia'], rating: 8.5, posterPath: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', synopsis: 'La codiciosa familia Ki-taek se infiltra en la vida de la próspera familia Park.' },
  { id: 93405,  tmdbId: 93405,  type: 'tv',    title: 'Squid Game', year: 2021, genres: ['Drama', 'Thriller'], rating: 8.0, posterPath: '/1QdXdRYfktUSONkl1oD5gc6Be0s.jpg', synopsis: 'Cientos de jugadores desesperados aceptan participar en juegos infantiles con consecuencias mortales.' },
  { id: 60059,  tmdbId: 60059,  type: 'tv',    title: 'Better Call Saul', year: 2015, genres: ['Drama', 'Crimen'], rating: 9.0, posterPath: '/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg', synopsis: 'La transformación de Jimmy McGill, un abogado honesto, en el corrupto Saul Goodman.' },
  { id: 2316,   tmdbId: 2316,   type: 'tv',    title: 'The Office', year: 2005, genres: ['Comedia'], rating: 9.0, posterPath: '/7DJKHzAi83BmQrWLrYYOqcoKfhR.jpg', synopsis: 'El día a día en las oficinas de Dunder Mifflin, filmado como un documental.' },
  { id: 61662,  tmdbId: 61662,  type: 'tv',    title: "Schitt's Creek", year: 2015, genres: ['Comedia'], rating: 8.4, posterPath: '/iRfSzrPS5VYWQv7KVSEg2BZZL6C.jpg', synopsis: 'Una familia millonaria pierde su fortuna y debe mudarse a un pueblo que compraron como chiste.' },
  { id: 97546,  tmdbId: 97546,  type: 'tv',    title: 'Ted Lasso', year: 2020, genres: ['Comedia', 'Drama'], rating: 8.8, posterPath: '/5fhZdwP1DVJ0FyVH6vrFdHwpXIn.jpg', synopsis: 'Un entrenador de fútbol americano sin experiencia es contratado para dirigir un club inglés.' },
  { id: 67070,  tmdbId: 67070,  type: 'tv',    title: 'Fleabag', year: 2016, genres: ['Comedia', 'Drama'], rating: 8.7, posterPath: '/27vEYsRKa3eAniwmoccOoluEXQ1.jpg', synopsis: 'Una mujer navega el caos de la vida moderna en Londres con humor e irreverencia.' },
  { id: 840430, tmdbId: 840430, type: 'movie', title: 'The Holdovers', year: 2023, genres: ['Comedia', 'Drama'], rating: 8.0, posterPath: '/VHSzNBTwxV8vh7wylo7O9CLdac.jpg', synopsis: 'Un profesor malhumorado debe quedarse en la escuela durante las vacaciones con un alumno problemático.' },
  { id: 639,    tmdbId: 639,    type: 'movie', title: 'When Harry Met Sally', year: 1989, genres: ['Comedia', 'Romance'], rating: 7.7, posterPath: '/rFOiFUhTMtDetqCGClC9PIgnC1P.jpg', synopsis: '¿Pueden hombres y mujeres ser amigos? La pregunta que se hacen Harry y Sally durante 12 años.' },
  { id: 492188, tmdbId: 492188, type: 'movie', title: 'Marriage Story', year: 2019, genres: ['Drama', 'Romance'], rating: 8.1, posterPath: '/2JRyCKaRKyJAVpsIHeLvPw5nHmw.jpg', synopsis: 'Un actor y una directora de teatro atraviesan un divorcio que cambia sus vidas.' },
  { id: 89905,  tmdbId: 89905,  type: 'tv',    title: 'Normal People', year: 2020, genres: ['Drama', 'Romance'], rating: 8.2, posterPath: '/c4mk4EQVIM11yd3W43DDdqDazDU.jpg', synopsis: 'La complicada relación de dos jóvenes irlandeses desde la adolescencia hasta la adultez.' },
  { id: 1399,   tmdbId: 1399,   type: 'tv',    title: 'Game of Thrones', year: 2011, genres: ['Fantasía', 'Drama'], rating: 9.2, posterPath: '/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg', synopsis: 'Varias familias luchan por el control del Trono de Hierro en los Siete Reinos.' },
  { id: 129,    tmdbId: 129,    type: 'movie', title: 'El viaje de Chihiro', year: 2001, genres: ['Animación', 'Fantasía'], rating: 8.6, posterPath: '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg', synopsis: 'Una niña queda atrapada en un mundo mágico y debe trabajar para liberar a sus padres.' },
  { id: 155,    tmdbId: 155,    type: 'movie', title: 'The Dark Knight', year: 2008, genres: ['Acción', 'Drama', 'Crimen'], rating: 9.0, posterPath: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg', synopsis: 'Batman enfrenta a El Joker, un criminal que quiere sumir Gotham en el caos.' },
  { id: 419430, tmdbId: 419430, type: 'movie', title: 'Get Out', year: 2017, genres: ['Terror', 'Thriller'], rating: 7.7, posterPath: '/mE24wUCfjK8AoBBjaMjho7Rczr7.jpg', synopsis: 'Un hombre afroamericano visita a los padres de su novia blanca y descubre algo perturbador.' },
  { id: 482571, tmdbId: 482571, type: 'movie', title: 'Hereditary', year: 2018, genres: ['Terror', 'Drama'], rating: 7.3, posterPath: '/ovKGh59VfqcsbOcVXCPzHzHVhji.jpg', synopsis: 'Tras la muerte de su madre, una familia comienza a descubrir oscuros secretos familiares.' },
  { id: 76341,  tmdbId: 76341,  type: 'movie', title: 'Mad Max: Fury Road', year: 2015, genres: ['Acción', 'Aventura'], rating: 8.1, posterPath: '/hA2ple9q4qnwxp3hKVNhroipsir.jpg', synopsis: 'En un futuro postapocalíptico, Max y Furiosa huyen de un tirano a través del desierto.' },
  { id: 95396,  tmdbId: 95396,  type: 'tv',    title: 'Severance', year: 2022, genres: ['Thriller', 'Ciencia Ficción'], rating: 8.7, posterPath: '/pPHpeI2X1qEd1CS1SeyrdhZ4qnT.jpg', synopsis: 'Empleados cuya memoria laboral y personal está quirúrgicamente dividida en dos mundos separados.' },
  { id: 545611, tmdbId: 545611, type: 'movie', title: 'Everything Everywhere All at Once', year: 2022, genres: ['Acción', 'Comedia', 'Ciencia Ficción'], rating: 8.0, posterPath: '/u68AjlvlutfEIcpmbYpKcdi09ut.jpg', synopsis: 'Una mujer inmigrante descubre que debe conectar con sus yo alternos del multiverso.' },
  { id: 111803, tmdbId: 111803, type: 'tv',    title: 'The White Lotus', year: 2021, genres: ['Drama', 'Comedia'], rating: 7.9, posterPath: '/gbSaK9v1CbcYH1ISgbM7XObD2dW.jpg', synopsis: 'Las vidas de los huéspedes y empleados de un resort de lujo se entrelazan con consecuencias inesperadas.' },
  { id: 666277, tmdbId: 666277, type: 'movie', title: 'Past Lives', year: 2023, genres: ['Drama', 'Romance'], rating: 7.9, posterPath: '/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg', synopsis: 'Dos amigos de infancia coreanos se reencuentran décadas después en Nueva York.' },
];
