// Mock titles con poster paths reales de TMDB
// Usado como fallback si la API de TMDB no está disponible.
// posterPath copiado de TMDB para los títulos del onboarding.

import type { NormalizedTitle } from '../services/tmdb';

export const MOCK_TITLES: NormalizedTitle[] = [
  { id: 278,    tmdbId: 278,    type: 'movie', title: 'The Shawshank Redemption', year: 1994, genres: ['Drama'], rating: 9.3, posterPath: '/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg', synopsis: 'Dos hombres unidos por la amistad en la dura prisión de Shawshank. Una historia de esperanza.' },
  { id: 4253,   tmdbId: 4253,   type: 'tv',    title: 'Band of Brothers', year: 2001, genres: ['Drama', 'Bélica'], rating: 9.4, posterPath: '/yVHnpzLPNKRhPRoVhD0FTJjDOOj.jpg', synopsis: 'La historia de la Compañía Easy del 506° Regimiento de Infantería Paracaidista durante la Segunda Guerra Mundial.' },
  { id: 87108,  tmdbId: 87108,  type: 'tv',    title: 'Chernobyl', year: 2019, genres: ['Drama', 'Historia'], rating: 9.3, posterPath: '/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg', synopsis: 'La historia real del desastre nuclear de 1986 en Chernóbil.' },
  { id: 73586,  tmdbId: 73586,  type: 'tv',    title: 'Succession', year: 2018, genres: ['Drama', 'Comedia'], rating: 8.9, posterPath: '/e2X8oy7ZBvhFT7XgdGFkFiSlqbx.jpg', synopsis: 'La familia Roy lucha por el control de su imperio mediático mientras el patriarca enferma.' },
  { id: 126308, tmdbId: 126308, type: 'tv',    title: 'Shōgun', year: 2024, genres: ['Drama', 'Historia'], rating: 8.9, posterPath: '/7O4iVfOMQmdCSMRuFJCBpBCcaNk.jpg', synopsis: 'Un navegante inglés llega al Japón feudal y se convierte en aliado de un señor de la guerra.' },
  { id: 872585, tmdbId: 872585, type: 'movie', title: 'Oppenheimer', year: 2023, genres: ['Drama', 'Historia'], rating: 8.5, posterPath: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg', synopsis: 'La historia del padre de la bomba atómica y el Proyecto Manhattan.' },
  { id: 1396,   tmdbId: 1396,   type: 'tv',    title: 'Breaking Bad', year: 2008, genres: ['Drama', 'Crimen'], rating: 9.5, posterPath: '/ggFHVNu6YYI5L9pCfOacjizRGt.jpg', synopsis: 'Un profesor de química con cáncer comienza a fabricar metanfetamina con un ex alumno.' },
  { id: 1398,   tmdbId: 1398,   type: 'tv',    title: 'The Sopranos', year: 1999, genres: ['Drama', 'Crimen'], rating: 9.2, posterPath: '/rTc7ZXdroqjkKivFPvCPX0Ru7UM.jpg', synopsis: 'Tony Soprano equilibra su vida familiar con su papel como jefe de la mafia de Nueva Jersey.' },
  { id: 680,    tmdbId: 680,    type: 'movie', title: 'Pulp Fiction', year: 1994, genres: ['Crimen', 'Drama'], rating: 8.9, posterPath: '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg', synopsis: 'Las historias entrelazadas de criminales, boxeadores y un par de asesinos en el Los Ángeles criminal.' },
  { id: 496243, tmdbId: 496243, type: 'movie', title: 'Parasite', year: 2019, genres: ['Thriller', 'Drama', 'Comedia'], rating: 8.5, posterPath: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', synopsis: 'La codiciosa familia Ki-taek se infiltra en la vida de la próspera familia Park.' },
  { id: 93405,  tmdbId: 93405,  type: 'tv',    title: 'Squid Game', year: 2021, genres: ['Drama', 'Thriller'], rating: 8.0, posterPath: '/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg', synopsis: 'Cientos de jugadores desesperados aceptan participar en juegos infantiles con consecuencias mortales.' },
  { id: 60059,  tmdbId: 60059,  type: 'tv',    title: 'Better Call Saul', year: 2015, genres: ['Drama', 'Crimen'], rating: 9.0, posterPath: '/fC2HDm5t0kHl7mTm7jxMR31b7by.jpg', synopsis: 'La transformación de Jimmy McGill, un abogado honesto, en el corrupto Saul Goodman.' },
  { id: 2316,   tmdbId: 2316,   type: 'tv',    title: 'The Office', year: 2005, genres: ['Comedia'], rating: 9.0, posterPath: '/7DJKHzAi83BmQrWLrYYOqcoKfhR.jpg', synopsis: 'El día a día en las oficinas de Dunder Mifflin, filmado como un documental.' },
  { id: 64216,  tmdbId: 64216,  type: 'tv',    title: "Schitt's Creek", year: 2015, genres: ['Comedia'], rating: 8.4, posterPath: '/4Bd4PQnjkiGaGfRqhR3QVlUQAJt.jpg', synopsis: 'Una familia millonaria pierde su fortuna y debe mudarse a un pueblo que compraron como chiste.' },
  { id: 97546,  tmdbId: 97546,  type: 'tv',    title: 'Ted Lasso', year: 2020, genres: ['Comedia', 'Drama'], rating: 8.8, posterPath: '/5fhZdwP1DVJ0FyVH6vrFdHwpXIn.jpg', synopsis: 'Un entrenador de fútbol americano sin experiencia es contratado para dirigir un club inglés.' },
  { id: 66788,  tmdbId: 66788,  type: 'tv',    title: 'Fleabag', year: 2016, genres: ['Comedia', 'Drama'], rating: 8.7, posterPath: '/2nPqcFdQWCyHe8kELlHLOoF1bnS.jpg', synopsis: 'Una mujer navega el caos de la vida moderna en Londres con humor e irreverencia.' },
  { id: 753342, tmdbId: 753342, type: 'movie', title: 'The Holdovers', year: 2023, genres: ['Comedia', 'Drama'], rating: 8.0, posterPath: '/VHSzNBTwxV8vh7wylo7P7yCTFm.jpg', synopsis: 'Un profesor malhumorado debe quedarse en la escuela durante las vacaciones con un alumno problemático.' },
  { id: 639,    tmdbId: 639,    type: 'movie', title: 'When Harry Met Sally', year: 1989, genres: ['Comedia', 'Romance'], rating: 7.7, posterPath: '/3f43bJhQbJVu8IonoIbnizXzPe1.jpg', synopsis: '¿Pueden hombres y mujeres ser amigos? La pregunta que se hacen Harry y Sally durante 12 años.' },
  { id: 492188, tmdbId: 492188, type: 'movie', title: 'Marriage Story', year: 2019, genres: ['Drama', 'Romance'], rating: 8.1, posterPath: '/pZekG6xabTmZxjmYw10YYtdVSaB.jpg', synopsis: 'Un actor y una directora de teatro atraviesan un divorcio que cambia sus vidas.' },
  { id: 103596, tmdbId: 103596, type: 'tv',    title: 'Normal People', year: 2020, genres: ['Drama', 'Romance'], rating: 8.2, posterPath: '/gPbM0MK8CP8A174rmUwGsADNYKD.jpg', synopsis: 'La complicada relación de dos jóvenes irlandeses desde la adolescencia hasta la adultez.' },
  { id: 1399,   tmdbId: 1399,   type: 'tv',    title: 'Game of Thrones', year: 2011, genres: ['Fantasía', 'Drama'], rating: 9.2, posterPath: '/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg', synopsis: 'Varias familias luchan por el control del Trono de Hierro en los Siete Reinos.' },
  { id: 129,    tmdbId: 129,    type: 'movie', title: 'El viaje de Chihiro', year: 2001, genres: ['Animación', 'Fantasía'], rating: 8.6, posterPath: '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg', synopsis: 'Una niña queda atrapada en un mundo mágico y debe trabajar para liberar a sus padres.' },
  { id: 155,    tmdbId: 155,    type: 'movie', title: 'The Dark Knight', year: 2008, genres: ['Acción', 'Drama', 'Crimen'], rating: 9.0, posterPath: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg', synopsis: 'Batman enfrenta a El Joker, un criminal que quiere sumir Gotham en el caos.' },
  { id: 419430, tmdbId: 419430, type: 'movie', title: 'Get Out', year: 2017, genres: ['Terror', 'Thriller'], rating: 7.7, posterPath: '/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg', synopsis: 'Un hombre afroamericano visita a los padres de su novia blanca y descubre algo perturbador.' },
  { id: 482571, tmdbId: 482571, type: 'movie', title: 'Hereditary', year: 2018, genres: ['Terror', 'Drama'], rating: 7.3, posterPath: '/p99pDhFBuLIAFqHBAOsEb8LGKsa.jpg', synopsis: 'Tras la muerte de su madre, una familia comienza a descubrir oscuros secretos familiares.' },
  { id: 76341,  tmdbId: 76341,  type: 'movie', title: 'Mad Max: Fury Road', year: 2015, genres: ['Acción', 'Aventura'], rating: 8.1, posterPath: '/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg', synopsis: 'En un futuro postapocalíptico, Max y Furiosa huyen de un tirano a través del desierto.' },
  { id: 95396,  tmdbId: 95396,  type: 'tv',    title: 'Severance', year: 2022, genres: ['Thriller', 'Ciencia Ficción'], rating: 8.7, posterPath: '/lMoEGTbXkKIAGaUa96K5k3aREpM.jpg', synopsis: 'Empleados cuya memoria laboral y personal está quirúrgicamente dividida en dos mundos separados.' },
  { id: 545611, tmdbId: 545611, type: 'movie', title: 'Everything Everywhere All at Once', year: 2022, genres: ['Acción', 'Comedia', 'Ciencia Ficción'], rating: 8.0, posterPath: '/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg', synopsis: 'Una mujer inmigrante descubre que debe conectar con sus yo alternos del multiverso.' },
  { id: 119051, tmdbId: 119051, type: 'tv',    title: 'The White Lotus', year: 2021, genres: ['Drama', 'Comedia'], rating: 7.9, posterPath: '/bCGCe1pAc9jQmoyOHGMpBhgKGjO.jpg', synopsis: 'Las vidas de los huéspedes y empleados de un resort de lujo se entrelazan con consecuencias inesperadas.' },
  { id: 951491, tmdbId: 951491, type: 'movie', title: 'Past Lives', year: 2023, genres: ['Drama', 'Romance'], rating: 7.9, posterPath: '/k3waqVXSnFLOhBxBHZYDQjhFPMM.jpg', synopsis: 'Dos amigos de infancia coreanos se reencuentran décadas después en Nueva York.' },
];
